### ISSUE TITLE
講師情報にユニークURL

### ISSUE THREAD

**Issue by hayakasa** [osokayama/osokayama.github.io#125]
講師情報にGETパラメータ付けるとかして直リンが張れるようにしといたほうが良いかな、とふと思ったのですが実装難易度どんなですかね
vue.js触ったことないので簡単そうならやってみたい

**Comment by shizone** [comment]
一旦ハッシュで実装を試みたんだけど戻ったときに一番上にスクロールしてしまい「まあまたいつかでええか」となった経緯があるんすけどパラメータだとどうだろ
(実装するだけならそんな難しいもんでもないと思う)

**Comment by hayakasa** [comment]
あースクロール位置は面倒そう。ちょっと探ってみますわ

**Comment by hayakasa** [comment]
脳内検討した結果、現状のモーダル出す仕組みはそのままで、GETパラメーターがついてたら読み込み時にモーダル開くイベントをfireしてスクロール位置も変更すればよさげ
（実装レベルで見てないので実際に実装できるかは別の話）

**Comment by shizone** [comment]
モーダル出さずに詳細ページ作ったほうがええなという結論に個人的になったので2020はその方針でいきたい

**Comment by shizone** [comment]
https://github.com/osokayama/osokayama.github.io/pull/154
で詳細ページを作ったのでクローズします
