### ISSUE TITLE
トップページの「お申込み開始までしばらくお待ち下さい」の変更

### ISSUE THREAD

**Issue by qt-luigi** [osokayama/osokayama.github.io#167]

**Comment by qt-luigi** [comment]
OSO2021のconnpassページ（https://oso.connpass.com/event/225435/）がオープンになったため、トップページ（https://okayama.open-seminar.org/）の「お申込み開始までしばらくお待ち下さい」の文言の変更およびconnpassへのリンク追加をお願い致します。

**Comment by shizone** [comment]
サイトに反映しました！ご連絡ありがとうございました。

**Comment by qt-luigi** [comment]
対応ありがとうございます！申し込み者が救われます！
