### ISSUE TITLE
展示のページを作成する

### ISSUE THREAD

**Issue by kazuhisa** [osokayama/osokayama.github.io#31]
[サイボウズlive](https://cybozulive.com/1_239522/gwBoard/view?bid=1%3A4141581&boffset=0&currentFolderId=947808#dummy=1461826167053)

* メニューにアイコンを追加
* 独立したページを作成する

**Comment by kazuhisa** [comment]
アイコンは[fortawesome](https://fortawesome.github.io/Font-Awesome/icons/)のを使えばいいらしい

**Comment by kazuhisa** [comment]
@makowis 
よく分からなくなってきたんだけど、全体的に改行コードは何で行けばいいの？LF? CRLF?

**Comment by kazuhisa** [comment]
CRLF のUTF8かな？

**Comment by makowis** [comment]
@kazuhisa あーバラバラになっちゃってますね・・・CRLFのUTF８で

**Comment by kazuhisa** [comment]
了解。ありがとう
