### ISSUE TITLE
最低限の情報で2017年版のページをオープンさせる

### ISSUE THREAD

**Issue by kazuhisa** [osokayama/osokayama.github.io#37]
# トップページ
![screencapture-okayama-open-seminar-org-1487675759687](https://cloud.githubusercontent.com/assets/370800/23162753/e44f247c-f872-11e6-848c-621dde035733.png)

# 開催概要
![screencapture-okayama-open-seminar-org-about-html-1487675944943](https://cloud.githubusercontent.com/assets/370800/23162920/a919ffd4-f873-11e6-97ac-78ef04544ab8.png)

# 協賛・協力・後援団体
![screencapture-okayama-open-seminar-org-sponsor-html-1487676276152](https://cloud.githubusercontent.com/assets/370800/23163001/04fd4b44-f874-11e6-9ec6-0234b404403f.png)

# スポンサーについて
サイボウズLiveの内容を参照すること

**Comment by kazuhisa** [comment]
@makowis 
「協賛・協力・後援団体」だけど、今回は無しですかね？

**Comment by shizone** [comment]
非表示にしているページは一旦削除しちゃっていいですよね
(立ち上げるタイミングで2016年から持ってくればいいので)

**Comment by shizone** [comment]
トップの写真はこの辺に差し替えようと思います
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/zephiransas/26773782000/in/album-72157665996522334/" title="DSC_5072"><img src="https://c1.staticflickr.com/8/7044/26773782000_50e01f7754_z.jpg" width="640" height="428" alt="DSC_5072"></a>

**Comment by makowis** [comment]
@kazuhisa 
>「協賛・協力・後援団体」だけど、今回は無しですかね？
それぞれ今手続きを進めてる段階だと思うので、各申請してくれてる人たちに確認ですね。
正式に決まってから掲載が良いかと。

**Comment by makowis** [comment]
@shizone 

> 非表示にしているページは一旦削除しちゃっていいですよね
> (立ち上げるタイミングで2016年から持ってくればいいので)

そうですね。一旦削除してしまっていいかと思います。

**Comment by shizone** [comment]
そういえばOrganizationの中の人になりたいのでよろしくお願いします

**Comment by kazuhisa** [comment]
> 非表示にしているページは一旦削除しちゃっていいですよね
> (立ち上げるタイミングで2016年から持ってくればいいので)

いいですよ 😸

**Comment by kazuhisa** [comment]
> そういえばOrganizationの中の人になりたいのでよろしくお願いします

招待しておきました〜。Admin権限にしておいたので、 @shizone の判断でどんどん追加してくれてOKです。

**Comment by kazuhisa** [comment]
> トップの写真はこの辺に差し替えようと思います

見落としてた。Good!

**Comment by makowis** [comment]
これfeature/2017みたいなブランチ切ってそこにプルリク投げて貰ったほうが、作業分担とかも出来ていいですかね？

**Comment by kazuhisa** [comment]
ブランチに対してプルリクを出すほどでは無いと思います。

@shizone 
作成途中でも良いので
**[wip]2017年版ページ**みたいに[wip]を付けてmasterブランチに対してプルリクを投げておいてください。
細かい調整はそのブランチで行っていきましょう。

**Comment by TakahashiIkki** [comment]
JOINしました。
Githubでの開発って、こんな感じで、進んでいくんですね。 

業務後、また、確認しておきます。

**Comment by shizone** [comment]
あ、しもた、[wip]つけるの忘れとった…

**Comment by makowis** [comment]
こちらオープンしたので閉じますね
