### ISSUE TITLE
いい感じのOGイメージを設定する

### ISSUE THREAD

**Issue by makowis** [osokayama/osokayama.github.io#39]
Facebookでシェアした時に設定されていないので、シェア画像としてCPIさんのバナーが表示されてしまう

**Comment by kazuhisa** [comment]
OGイメージってなんぞや？と思ってググってみた。
https://blog.sixapart.jp/2012-06/ogimage.html

とりあえずロゴで良いのでは？と思うのだが @shizone @TakahashiIkki  はなにか掲載したいイメージありますか？

**Comment by shizone** [comment]
2014-2015年版だとトップの写真が出るように調整してたような気がするので写真かなぁと言う気もしますが、専用にロゴを重ねた画像を錬成するのもアリかもしれませんなぁ

**Comment by kazuhisa** [comment]
> 専用にロゴを重ねた画像を錬成するのもアリかもしれませんなぁ

いいですね。会場の雰囲気が伝わって良いと思います。
お手数ですが、トップの写真にロゴを重ねた画像を作ってOGイメージとして登録して頂けますか？ 🙇

**Comment by shizone** [comment]
今日ちょうど晩にもくもくする用事があるのでやっときますね

**Comment by kazuhisa** [comment]
やったー。ありがとうございます！

**Comment by makowis** [comment]
@shizone ありがとうございます！

**Comment by shizone** [comment]
あ、というかこれ、うまくいってるか確認するためにエイヤでマージしてから確認するしかないんですかね…。
(クールなソリューションをご存知であれば教えていただきたく)

**Comment by kazuhisa** [comment]
エイヤでマージで問題ないでしょう。画面上に間違った情報が表示されるわけでもないですし。
うまく行かなければもう一度プルリクを出すか、試行錯誤が必要であれば本件に関しては直接masterにpushしても良いかと思います。

**Comment by makowis** [comment]
@shizone まぁ今がアレなのでエイヤで問題ないかと。

Facebookの確認はこちらで出来ます
https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fokayama.open-seminar.org%2F

**Comment by eiel** [comment]
ステージング用リポジトリ作って確認するとか(相対パスしたいならドメイン振れば良い気がしなくもない。

**Comment by makowis** [comment]
エイヤでリリースしてしまった

**Comment by makowis** [comment]
いい感じです
![2017-02-23 20 16 26](https://cloud.githubusercontent.com/assets/1855927/23256971/fc724528-fa04-11e6-91ee-de90e4c1c1b4.png)
