### ISSUE TITLE
DNSの設定を行う

### ISSUE THREAD

**Issue by kiyokura** [osokayama/osokayama.github.io#4]
http://okayama.open-seminar.org/ の向き先をこちらに変える

必要な作業:
- DNSサーバ側の作業
    - レジストラで利用しているDNSのAレコードの設定を変更
- このリポジトリで必要な作業
    - CNAMEファイルを作成（リポジトリのルートに作成）

参考:
- [自分のGitHub Pagesと独自ドメインの設定方法](http://qiita.com/mofumofu3n/items/b859fb3c5d924cfcca15)

**Comment by ryosms** [comment]
@kiyokura DNSの設定をお願いします

**Comment by kiyokura** [comment]
DNSの設定しました。
TTL3600だったので、数時間もすれば新しいほうが返ってくると思います。
ブラウザから新しいほうが確認できたらクローズします。
（もしくは確認できた人がクローズしてください）

**Comment by kiyokura** [comment]
http://okayama.open-seminar.org/で新しいほう（トップが2016）が見れたのでOKっぽい
