### ISSUE TITLE
トップにソーシャルボタンを設置

### ISSUE THREAD

**Issue by shizone** [osokayama/osokayama.github.io#40]
したいです

**Comment by shizone** [comment]
イメッジ的にはこういう感じ
https://www.microsoft.com/ja-jp/events/decode/2017/

**Comment by kazuhisa** [comment]
@shizone 

いいですね〜。ぜひぜひお願いします 🙇🙇🙇

**Comment by shizone** [comment]
ではこっちもやっていきます

**Comment by makowis** [comment]
@shizone お願いします！

**Comment by shizone** [comment]
ボタンつけるならheaderの要素とmainの要素どっちに突っ込むべきですかねぇこれ

**Comment by kazuhisa** [comment]
![_2017_02_23_23_38](https://cloud.githubusercontent.com/assets/370800/23263300/28287644-fa21-11e6-87c8-cc8da49dc9a8.png)
headerってこの部分だよね？
であれば、ボタンつけるのはここじゃないかな。

**Comment by shizone** [comment]
じゃあmainのほうに放り込みますね。下側かなぁ

**Comment by kazuhisa** [comment]
え？いやいや、headerの中のほうが良いと思いました。

**Comment by shizone** [comment]
お、意味合い勘違いしてました。
現状headerの一番下に放り込んでいるので、その方針で進めていきますね。

**Comment by kazuhisa** [comment]
うんうん。
お願いします

**Comment by shizone** [comment]
JJUG CCCとかはソーシャルボタン一番上に置いてるんですよねぇ。これはこれで面白いかも知れない。
http://www.java-users.jp/ccc2016fall
