### ISSUE TITLE
開催概要: 今年のテーマが最初に書かれるべき

### ISSUE THREAD

**Issue by Nyoho** [osokayama/osokayama.github.io#41]
開催概要のページの今の設計について、今年のテーマが最初に書かれていた方がよいと思いました。

僕は、普通の感覚として、まずは今年のテーマはなんだろな、と思って開いたのです。
そしたら「2016年? ん? まだ更新されてないの?」と思います。
よく見たら、その下に2017年の記述があったのです。
通常のユーザビリティの感覚からすると、ユーザに「よく見させる」ことをしてはいけませんから、このように考えました。

どうでしょうか。ご一考下さいますようお願いいたします。

[開催概要 | オープンセミナー2017@岡山](https://okayama.open-seminar.org/about.html)

**Comment by makowis** [comment]
確かに最初にテーマがあった方がインパクトはありそうですね

**Comment by Nyoho** [comment]
追加情報を追加(重言)

**Comment by Nyoho** [comment]
インパクトというか、普通のユーザビリティ的な思考のフロウはこうじゃないかと思ったのです。

**Comment by makowis** [comment]
なるほど

**Comment by Nyoho** [comment]
こういう広く見てもらいたいウェブページは、開発者目線ではなく、ユーザ目線で作った方がいいと思います。

とはいえ、僕ではない思考を持ったユーザもいるでしょうから、まあご参考までにということで 😄

**Comment by makowis** [comment]
最初にオープンセミナーって何か分からないかなということで、オープンセミナーの説明を書いてたと思います

**Comment by shizone** [comment]
JJUG CCCとかだとこの辺の位置ですなぁ。
http://www.java-users.jp/ccc2016fall/#about

どういう感じに配置するといい感じに収まるだろう

**Comment by shizone** [comment]
あ、勘違いしてた。aboutの順番か

**Comment by makowis** [comment]
ですです

**Comment by makowis** [comment]
こんな感じ？
https://github.com/osokayama/osokayama.github.io/pull/42

**Comment by Nyoho** [comment]
> 最初にオープンセミナーって何か分からないかなということで、オープンセミナーの説明を書いてたと思います

それは最初の2行で達成されています。
問題はその後に突然過去のテーマになるということです。
その後また、今年のテーマの記述になっているということが、僕は issue ではないかと思いました。
普通のユーザは頭が、今年に行かせられたり去年に行かせられたりと、揺さぶられている、と思ったのです。

もちろん僕はユーザビリティの専門家ではないので、非常にあれな意見の可能性も考えて、考える材料にしてください 😄

**Comment by makowis** [comment]
ということはどちらかというと過去の開催実績を後ろに持ってきた方がいいのでは？ということですか？

**Comment by eiel** [comment]
aboutってurlが混乱を招いてるかなとおもいます。
イベントの開催概要なのか、オープンセミナーについてのページなのか、そこが、混在してる状態にみえますね。

**Comment by shizone** [comment]
過去の開催実績については #5 のほうに持っていってしまえば解決かな？

**Comment by makowis** [comment]
それが出来ればそちらに持っていけば解決しそう

**Comment by eiel** [comment]
indexの下部に持ってくのもありかなー。#5 のほうが良さげだけど。

**Comment by makowis** [comment]
とりあえず混乱のもとになる開催実績をaboutの下の方に移動してみました
https://github.com/osokayama/osokayama.github.io/pull/42/files

**Comment by eiel** [comment]
オープンセミナーの説明いれるなら

オープンセミナーとは？

みたいなヘッダーがあるほうがいいかなと思いました。
開催概要なのに、オープンセミナーの説明が書いてあって少し混乱します。

オープンセミナー2017@岡山の説明になってるならたぶん混乱しないかな。(でもそうじゃないよね

オープンセミナーのことなんて知ってるよ！毎年いってるよ！みたいな人をターゲットにするならテーマがどーん。のほうがわかりやすいです。


(主観で書いてます

**Comment by ryosms** [comment]
ロゴ以外に年度がないので、ぱっと見でいきなり「2016」って文字が入ってくるから俺も一瞬「ん？」とはなった

**Comment by kazuhisa** [comment]
#42 によっていきなり2016って文字が見えなくなり違和感は感じなくなりました。
また、オープンセミナー自体の説明は冒頭2行で十分だと感じています。

よって、ひとまず #42 をマージしようと思います。

@shizone @TakahashiIkki @makowis 意見を聞かせてください。

**Comment by makowis** [comment]
@kazuhisa 過去リンクが紛らわしい問題は一旦これで解消されるのでいいかなと思います

**Comment by shizone** [comment]
@kazuhisa マージしちゃっていいんじゃないでしょうか。今後の展開は必要に応じて別で立ててもいいと思います。

**Comment by kazuhisa** [comment]
マージしました。
@Nyoho さんが初めに書かれている問題は解消したと思うのでcloseしますね。
