### ISSUE TITLE
開催概要に2013年以前のページのリンクを追加したい

### ISSUE THREAD

**Issue by kiyokura** [osokayama/osokayama.github.io#5]
開催概要（about.html）に2013年以前ののリンクを追加しておきたい
- 2013年度 : http://openseminar.okaya.ma/2013/
- 2012年度 : http://openseminar.okaya.ma/2012/
- 2011年度 : http://openseminar.okaya.ma/2011/
- 2010年度 : http://openseminar.okaya.ma/2010/
- 2009年度 : http://openseminar.okaya.ma/2009/

**Comment by ryosms** [comment]
開催概要に入れてもいいけど、数が増えてくるとノイズになりそうなので
「過去の開催実績」みたいなページを作ってもいいかもしれない

**Comment by kiyokura** [comment]
『「過去の開催実績」ページを作る』に+1

**Comment by kazuhisa** [comment]
@kiyokura 
「過去の開催実績」ページを作っていただけるとありがたいです 🙇

**Comment by shizone** [comment]
やっていきます

**Comment by kazuhisa** [comment]
@shizone 
ありがとうございます 😸
