### ISSUE TITLE
about.htmlの開催概要を過去の開催実績の上に移動する

### ISSUE THREAD

**Issue by kazuhisa** [osokayama/osokayama.github.io#52]
![___ 2017_](https://cloud.githubusercontent.com/assets/370800/23326931/5e8ca7ba-fb47-11e6-8ade-4691faa509b8.png)

↓

![___ 2017_](https://cloud.githubusercontent.com/assets/370800/23326939/76d13732-fb47-11e6-82d7-ad27662d2c30.png)

**Comment by kazuhisa** [comment]
@TakahashiIkki 
お願いします 🙇

**Comment by TakahashiIkki** [comment]
やります！
