### ISSUE TITLE
テコラスさんの登壇者のプロフィール更新

### ISSUE THREAD

**Issue by makowis** [osokayama/osokayama.github.io#70]
角 俊和
NHNテコラス株式会社 執行役員

通信キャリア系ホスティング会社、リクルートを経て、2016年4月よりNHNテコラス株式会社 執行役員SME事業部事業部長。中小企業向けビジネスを担当

https://twitter.com/techsmith8/media
https://www.facebook.com/toshikazu.sumi?fref=ts

![17917009_1767431190235017_648115742_o](https://cloud.githubusercontent.com/assets/1855927/25038076/b13042ea-2137-11e7-81eb-d8401f3db84c.jpg)

**Comment by shizone** [comment]
https://frame.mangaloo.jp/l/693298/291708/579565
