### ISSUE TITLE
スマートフォンの表示の時に下層ページが崩れるので調整したい

### ISSUE THREAD

**Issue by makowis** [osokayama/osokayama.github.io#9]
![2016-02-20 11 19 37](https://cloud.githubusercontent.com/assets/1855927/13193865/e054a58e-d7c3-11e5-80e8-9d9c99925534.png)

**Comment by hayakasa** [comment]
http://foundation.zurb.com/sites/docs/v/5.5.3/components/offcanvas.html
Off Canvas メニューにするのが無難かなあと思ってます

**Comment by makowis** [comment]
@hayakasa ちょっとこれでやってみますね

**Comment by makowis** [comment]
あっこれfoundationか・・・

**Comment by hayakasa** [comment]
今さっと出せないけどメニュー単体のライブラリはたくさんあるのでお好きなのをどうぞ

**Comment by hayakasa** [comment]
http://tympanus.net/Development/SidebarTransitions/
http://tympanus.net/Development/OffCanvasMenuEffects/wave.html
http://tympanus.net/Development/PerspectivePageViewNavigation/

この辺をよく使ってる
